import { useState, useEffect } from "react";
import { Button } from "@/components/ui/button";
import { CheckCircle, Download, ExternalLink, Play, Apple, Loader2, Clock, AlertCircle } from "lucide-react";
import { supabase } from "@/integrations/supabase/client";

interface BuildResult {
  platform: string;
  status: string;
  buildId: string;
  message: string;
  estimatedTime: string;
  downloadUrl: string | null;
}

interface BuildSuccessStepProps {
  selectedPlatforms: string[];
  appName: string;
  onStartOver: () => void;
  buildResults?: BuildResult[];
}

const BuildSuccessStep = ({
  selectedPlatforms,
  appName,
  onStartOver,
  buildResults = [],
}: BuildSuccessStepProps) => {
  const [downloadingAndroid, setDownloadingAndroid] = useState(false);
  const [downloadingIos, setDownloadingIos] = useState(false);
  const [builds, setBuilds] = useState<BuildResult[]>(buildResults);

  // Subscribe to real-time build updates
  useEffect(() => {
    // Get build IDs to track
    const buildIds = buildResults.map(b => b.buildId);
    if (buildIds.length === 0) return;

    console.log('Subscribing to real-time updates for builds:', buildIds);

    const channel = supabase
      .channel('build-status-updates')
      .on(
        'postgres_changes',
        {
          event: '*',
          schema: 'public',
          table: 'builds',
        },
        (payload) => {
          console.log('Real-time build update received:', payload);
          
          const updatedBuild = payload.new as {
            build_id: string;
            platform: string;
            status: string;
            download_url: string | null;
            error_message: string | null;
          };

          // Update our local state if this build is one we're tracking
          setBuilds(prev => prev.map(build => {
            if (build.buildId === updatedBuild.build_id) {
              return {
                ...build,
                status: updatedBuild.status,
                downloadUrl: updatedBuild.download_url,
                message: updatedBuild.error_message || build.message,
              };
            }
            return build;
          }));
        }
      )
      .subscribe((status) => {
        console.log('Real-time subscription status:', status);
      });

    return () => {
      console.log('Unsubscribing from real-time updates');
      supabase.removeChannel(channel);
    };
  }, [buildResults]);

  const sanitizeFileName = (name: string) => {
    return name.replace(/[^a-zA-Z0-9]/g, '_').toLowerCase() || 'app';
  };

  const handleDownload = async (platform: 'android' | 'ios') => {
    const setDownloading = platform === 'android' ? setDownloadingAndroid : setDownloadingIos;
    setDownloading(true);

    const build = builds.find(b => b.platform === platform);
    
    if (build?.downloadUrl && !build.downloadUrl.startsWith('#demo')) {
      // Real download URL from Codemagic
      window.open(build.downloadUrl, '_blank');
      setDownloading(false);
      return;
    }

    // Demo/simulated download
    setTimeout(() => {
      const extension = platform === 'android' ? 'apk' : 'ipa';
      const mimeType = platform === 'android' 
        ? 'application/vnd.android.package-archive' 
        : 'application/octet-stream';

      const content = `# ${platform.toUpperCase()} Package
# Generated by Web2App Converter with Codemagic
# ================================
#
# App Name: ${appName}
# Platform: ${platform}
# Package Type: ${extension.toUpperCase()}
# Generated: ${new Date().toISOString()}
# Build ID: ${build?.buildId || 'demo'}
#
# This is a demo package. In production, this would be a real
# ${platform === 'android' ? 'Android APK' : 'iOS IPA'} file generated by Codemagic CI/CD.
#
# For production builds:
# 1. Configure your Codemagic account with signing credentials
# 2. The build will produce a real, signed app package
# 3. Download and submit to ${platform === 'android' ? 'Google Play Store' : 'Apple App Store'}

[METADATA]
app_name=${appName}
platform=${platform}
format=${extension}
build_service=codemagic
timestamp=${Date.now()}
`;

      const blob = new Blob([content], { type: mimeType });
      const url = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = url;
      link.download = `${sanitizeFileName(appName)}.${extension}`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(url);
      
      setDownloading(false);
    }, 1500);
  };

  const getBuildStatus = (platform: string) => {
    const build = builds.find(b => b.platform === platform);
    return build?.status || 'completed';
  };

  const renderBuildCard = (
    platform: 'android' | 'ios',
    icon: React.ReactNode,
    name: string,
    color: string
  ) => {
    const status = getBuildStatus(platform);
    const isDownloading = platform === 'android' ? downloadingAndroid : downloadingIos;
    const build = builds.find(b => b.platform === platform);

    return (
      <div className="flex items-center gap-3 p-4 rounded-xl border bg-card">
        <div className={`w-12 h-12 rounded-lg ${color} flex items-center justify-center`}>
          {icon}
        </div>
        <div className="flex-1">
          <p className="font-medium">{name}</p>
          <div className="flex items-center gap-1 text-xs text-muted-foreground">
            {status === 'queued' && (
              <>
                <Clock className="w-3 h-3" />
                <span>Queued - {build?.estimatedTime}</span>
              </>
            )}
            {status === 'building' && (
              <>
                <Loader2 className="w-3 h-3 animate-spin" />
                <span>Building...</span>
              </>
            )}
            {status === 'completed' && (
              <>
                <CheckCircle className="w-3 h-3 text-green-500" />
                <span>Ready to download</span>
              </>
            )}
            {status === 'failed' && (
              <>
                <AlertCircle className="w-3 h-3 text-red-500" />
                <span>Build failed</span>
              </>
            )}
          </div>
        </div>
        <Button
          size="sm"
          variant="outline"
          onClick={() => handleDownload(platform)}
          disabled={status !== 'completed' || isDownloading}
        >
          {isDownloading ? (
            <Loader2 className="w-4 h-4 animate-spin" />
          ) : (
            <Download className="w-4 h-4" />
          )}
        </Button>
      </div>
    );
  };

  return (
    <div className="space-y-6 animate-fade-in text-center">
      <div className="w-20 h-20 rounded-full bg-green-500/10 flex items-center justify-center mx-auto">
        <CheckCircle className="w-10 h-10 text-green-500" />
      </div>

      <div>
        <h2 className="text-2xl font-bold mb-2">Build Started!</h2>
        <p className="text-muted-foreground">
          Your app "{appName}" is being built via Codemagic
        </p>
      </div>

      {/* Build Status Cards */}
      <div className="max-w-md mx-auto space-y-3">
        {selectedPlatforms.includes("android") && 
          renderBuildCard(
            'android',
            <Play className="w-5 h-5 text-green-600" />,
            'Android APK',
            'bg-green-500/10'
          )
        }
        {selectedPlatforms.includes("ios") && 
          renderBuildCard(
            'ios',
            <Apple className="w-5 h-5 text-blue-600" />,
            'iOS IPA',
            'bg-blue-500/10'
          )
        }
      </div>

      {/* Build Info */}
      <div className="bg-accent/50 rounded-xl p-4 max-w-md mx-auto">
        <p className="text-sm text-muted-foreground">
          Builds are processed by Codemagic CI/CD. You'll be notified when your builds are ready. 
          Typical build time is 5-15 minutes.
        </p>
      </div>

      {/* Next Steps */}
      <div className="bg-card border rounded-xl p-6 max-w-md mx-auto text-left">
        <h3 className="font-semibold mb-3">Next Steps</h3>
        <ul className="space-y-2 text-sm text-muted-foreground">
          <li className="flex items-start gap-2">
            <span className="w-5 h-5 rounded-full bg-primary/10 text-primary flex items-center justify-center text-xs mt-0.5 shrink-0">1</span>
            <span>Wait for builds to complete (check status above)</span>
          </li>
          <li className="flex items-start gap-2">
            <span className="w-5 h-5 rounded-full bg-primary/10 text-primary flex items-center justify-center text-xs mt-0.5 shrink-0">2</span>
            <span>Download your app files</span>
          </li>
          <li className="flex items-start gap-2">
            <span className="w-5 h-5 rounded-full bg-primary/10 text-primary flex items-center justify-center text-xs mt-0.5 shrink-0">3</span>
            <span>Test on device, then submit to app stores</span>
          </li>
        </ul>
      </div>

      {/* Documentation Links */}
      <div className="flex flex-col sm:flex-row gap-3 justify-center max-w-md mx-auto">
        <Button 
          variant="outline" 
          className="flex-1"
          onClick={() => window.open('https://docs.codemagic.io', '_blank')}
        >
          <ExternalLink className="w-4 h-4 mr-2" />
          Codemagic Docs
        </Button>
        <Button 
          variant="outline" 
          className="flex-1"
          onClick={() => window.open('https://play.google.com/console', '_blank')}
        >
          <ExternalLink className="w-4 h-4 mr-2" />
          Play Console
        </Button>
      </div>

      <div className="pt-4">
        <Button variant="ghost" onClick={onStartOver}>
          Create Another App
        </Button>
      </div>
    </div>
  );
};

export default BuildSuccessStep;
