import { useEffect, useRef, useState } from "react";
import { Smartphone, Monitor, RefreshCw, ExternalLink } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Skeleton } from "@/components/ui/skeleton";

interface ExpoSnackPreviewProps {
  websiteUrl: string;
  appName: string;
  enableNavigation: boolean;
  navItems: Array<{ label: string; url: string; icon: string }>;
}

const ExpoSnackPreview = ({
  websiteUrl,
  appName,
  enableNavigation,
  navItems,
}: ExpoSnackPreviewProps) => {
  const containerRef = useRef<HTMLDivElement>(null);
  const [platform, setPlatform] = useState<"ios" | "android" | "web">("ios");
  const [loading, setLoading] = useState(true);
  const [key, setKey] = useState(0);

  // Generate the Expo Snack code
  const generateSnackCode = () => {
    const navCode = enableNavigation && navItems.length > 0
      ? `
import { createBottomTabNavigator } from '@react-navigation/bottom-tabs';
import { NavigationContainer } from '@react-navigation/native';
import { Ionicons } from '@expo/vector-icons';

const Tab = createBottomTabNavigator();
const navItems = ${JSON.stringify(navItems)};

function AppNavigator() {
  return (
    <Tab.Navigator
      screenOptions={({ route }) => ({
        tabBarIcon: ({ focused, color, size }) => {
          const item = navItems.find(n => n.label === route.name);
          const iconName = item?.icon || 'home';
          return <Ionicons name={iconName} size={size} color={color} />;
        },
      })}
    >
      {navItems.map((item, index) => (
        <Tab.Screen 
          key={index}
          name={item.label} 
          children={() => <WebViewScreen url={"${websiteUrl}" + item.url} />}
        />
      ))}
    </Tab.Navigator>
  );
}`
      : '';

    return `
import React from 'react';
import { StatusBar, StyleSheet, SafeAreaView, Platform, View, Text, ActivityIndicator } from 'react-native';
import { WebView } from 'react-native-webview';
${enableNavigation ? "import { NavigationContainer } from '@react-navigation/native';" : ''}
${navCode}

function WebViewScreen({ url = '${websiteUrl || 'https://expo.dev'}' }) {
  const [loading, setLoading] = React.useState(true);
  
  return (
    <SafeAreaView style={styles.container}>
      <StatusBar barStyle="dark-content" />
      {loading && (
        <View style={styles.loadingContainer}>
          <ActivityIndicator size="large" color="#6366f1" />
          <Text style={styles.loadingText}>Loading ${appName || 'App'}...</Text>
        </View>
      )}
      <WebView
        source={{ uri: url }}
        style={[styles.webview, loading && styles.hidden]}
        javaScriptEnabled={true}
        domStorageEnabled={true}
        startInLoadingState={false}
        onLoadEnd={() => setLoading(false)}
        scalesPageToFit={true}
        allowsInlineMediaPlayback={true}
      />
    </SafeAreaView>
  );
}

export default function App() {
  ${enableNavigation && navItems.length > 0 
    ? `return (
    <NavigationContainer>
      <AppNavigator />
    </NavigationContainer>
  );` 
    : 'return <WebViewScreen />;'}
}

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#fff',
    paddingTop: Platform.OS === 'android' ? StatusBar.currentHeight : 0,
  },
  webview: {
    flex: 1,
  },
  hidden: {
    opacity: 0,
  },
  loadingContainer: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    justifyContent: 'center',
    alignItems: 'center',
    backgroundColor: '#fff',
    zIndex: 10,
  },
  loadingText: {
    marginTop: 12,
    fontSize: 16,
    color: '#666',
  },
});
`.trim();
  };

  const snackCode = generateSnackCode();
  const encodedCode = encodeURIComponent(snackCode);
  
  // Dependencies for the Snack
  const dependencies = enableNavigation
    ? "react-native-webview,@react-navigation/native,@react-navigation/bottom-tabs,react-native-screens,react-native-safe-area-context,@expo/vector-icons"
    : "react-native-webview";

  const snackUrl = `https://snack.expo.dev/embedded?platform=${platform}&name=${encodeURIComponent(appName || 'WebView App')}&description=${encodeURIComponent('Generated by Appify')}&code=${encodedCode}&dependencies=${encodeURIComponent(dependencies)}&preview=true&hideQueryParams=true&theme=dark&supportedPlatforms=ios,android,web&deviceFrame=true`;

  const handleRefresh = () => {
    setLoading(true);
    setKey(prev => prev + 1);
  };

  const openInSnack = () => {
    const fullUrl = `https://snack.expo.dev/?platform=${platform}&name=${encodeURIComponent(appName || 'WebView App')}&code=${encodedCode}&dependencies=${encodeURIComponent(dependencies)}`;
    window.open(fullUrl, '_blank');
  };

  useEffect(() => {
    setLoading(true);
  }, [websiteUrl, enableNavigation, navItems, platform]);

  return (
    <div className="flex flex-col h-full">
      {/* Controls */}
      <div className="flex items-center justify-between mb-4">
        <div className="flex items-center gap-2">
          <Button
            variant={platform === "ios" ? "default" : "outline"}
            size="sm"
            onClick={() => setPlatform("ios")}
          >
            <Smartphone className="w-4 h-4 mr-1" />
            iOS
          </Button>
          <Button
            variant={platform === "android" ? "default" : "outline"}
            size="sm"
            onClick={() => setPlatform("android")}
          >
            <Smartphone className="w-4 h-4 mr-1" />
            Android
          </Button>
          <Button
            variant={platform === "web" ? "default" : "outline"}
            size="sm"
            onClick={() => setPlatform("web")}
          >
            <Monitor className="w-4 h-4 mr-1" />
            Web
          </Button>
        </div>
        
        <div className="flex items-center gap-2">
          <Button variant="ghost" size="sm" onClick={handleRefresh}>
            <RefreshCw className="w-4 h-4" />
          </Button>
          <Button variant="ghost" size="sm" onClick={openInSnack}>
            <ExternalLink className="w-4 h-4" />
          </Button>
        </div>
      </div>

      {/* Preview Container */}
      <div 
        ref={containerRef}
        className="relative flex-1 bg-muted rounded-xl overflow-hidden min-h-[400px]"
      >
        {loading && (
          <div className="absolute inset-0 flex items-center justify-center bg-muted z-10">
            <div className="text-center">
              <Skeleton className="w-48 h-48 mx-auto rounded-xl mb-4" />
              <p className="text-sm text-muted-foreground">Loading preview...</p>
            </div>
          </div>
        )}
        
        <iframe
          key={key}
          src={snackUrl}
          className="w-full h-full border-0"
          onLoad={() => setLoading(false)}
          allow="accelerometer; ambient-light-sensor; camera; encrypted-media; geolocation; gyroscope; hid; microphone; midi; payment; usb; vr; xr-spatial-tracking"
          sandbox="allow-forms allow-modals allow-popups allow-presentation allow-same-origin allow-scripts"
          title="Expo Snack Preview"
        />
      </div>

      {/* Info */}
      <p className="text-xs text-muted-foreground mt-3 text-center">
        Live preview powered by Expo Snack SDK. Changes reflect in real-time.
      </p>
    </div>
  );
};

export default ExpoSnackPreview;
